Update for dmd 2.111
> socket.d(81,28): Error: undefined identifier `delete`
Remove the removed keyword `delete` and instead call the destructor with
`destroy`

> Deprecation: `return` statements cannot be in `scope(failure)` bodies.
Use try-catch instead of scope failure to change the return value.